# Site settings
title: 0hlov3
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 0hlov3
user_description: I'm a DevOps Engineer from Germany...
user_title: DevOps Engineer
email: 0hlov3@protonmail.com
twitter_username: 0hlov3s
instagram_username: 0hlov3s
facebook_username: 0hlov3
linkedin_username: 0hlov3
github_username:  0hlov3
# medium_username: 0hlov3
medium_url: 0hlov3.medium.com
# gplus_username:  lorem_ipsum
## FediVerse
mastodon_url: "mstdn.social/@0hlov3"
pixelfed_url: "pixelfed.social/Ohlov3"
matrix_url: "matrix.to/#/@0hlov3:matrix.fedi.tech"

exclude: ['package.json', 'src' , 'node_modules']
